qasite/pollsite/urls.py
from django.urls import path
from . import views

app_name="pollsite"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.Vote, name="vote"),
    
]

qasite/qasite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pollsite.urls')),
    path('admin/', admin.site.urls),
]

qasite/pollsite/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
    question_txt=models.CharField(("Question Text"), max_length=500) # Question Text will be the label on Django admin site once this model is registered
    pub_date=models.DateTimeField(("Date Published"))
    
    def __str__(self):
        return self.question_txt
    
    def recently_added(self):
        now=timezone.now()
        return now - datetime.timedelta(days=1) <=self.pub_date <= now #this takes the current time and subtracts a day. Then compares whether the question
                                                                            #has been posted from that time to recent.
                                                                            
class Answer(models.Model):
    question=models.ForeignKey(Question, on_delete=models.CASCADE) # Relationship, association
    answer_txt=models.CharField(max_length=100)
    votes=models.IntegerField(default=0)
    
    def __str__(self):
        return self.answer_txt # Once the answer is added, return its txt

qasite/pollsite/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.db.models import F

# import the models
from .models import Question, Answer

#ttimezone
from django.utils import timezone

# Create your views here.

#Using generic views
class IndexView(generic.ListView):
    template_name="pollsite/index.html"
    context_object_name= "latest_quiz_list"
    
    def get_queryset(self):
        # modify to make sure you cater for time prior to rendering the list of questions lte== less than or equal to
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
        # return Question.objects.order_by('-pub_date')
        
    
    
#details of the Question
class DetailView(generic.DetailView):
    model=Question
    template_name="pollsite/detail.html"
    

# vote Action
def Vote(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    try:
        selected_ans=question.answer_set.get(pk=request.POST['ans'])
    except(KeyError, Answer.DoesNotExist):
        return render(
            request,
            "pollsite/detail.html",
            {
                "question": question,
                "error_message": "You did not select an Answer",
            }
        )
        
    selected_ans.votes=F('votes') + 1
    selected_ans.save()
    return HttpResponseRedirect(reverse("pollsite:results", args=(question.id,))) # Redirect to results page 
        

#Results
class ResultsView(generic.DetailView):
    model= Question
    template_name= "pollsite/result.html"
    

qasite/pollsite/templates/pollsite/detail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>This is the page to view each Question and its answers</h1> <br/>
        
        {% comment %} <!--Display the question-->
   <h2>  {{ each_quiz.question_txt }} </h2>

        <!--list the possible answers-->
        {% for ans in each_quiz.answers_set.all %}
        <li> {{ans.answer_txt}}</li>
        {% endfor %}
         {% endcomment %}
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        <!--Form implementation-->
        <form action="{% url 'pollsite:vote' question.id%}" method="post">
            {% csrf_token %} <!--Security-->
            <fieldset>

                <legend><h1>{{ question.question_txt }}</h1></legend>

                {% if error_message %}<p style="color:red;"><strong>{{ error_message }}</strong></p>{% endif %}
                {% for ans in question.answer_set.all %}
                    <input type="radio" name="ans" id="ans{{ forloop.counter }}" value="{{ ans.id }}">
                    <label for="ans{ forloop.counter }}">{{ ans.answer_txt }}</label><br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
            </form> 
        
        <script src="" async defer></script>
    </body>
</html>

qasite/pollsite/templates/pollsite/index.html
<!--Load the css-->
{% load static %}

<link rel="stylesheet" href="{% static 'pollsite/style.css' %}">

  

<html>
    <head>
        <meta charset="utf-8">

        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title> Landing page </title>

         {% comment %} 
        Make the page load the css
        {% endcomment %}
     

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

       
        <!--[if lt IE 7]>

            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        
        
            <![endif]-->

        
        <script src="" async defer></script>
        <h4 >These are all the questions present under Index.html</h4>
        <input type="button" id="heading" value="Click!"> 
 
        {% if latest_quiz_list %}
    <ul>
    {% for question in latest_quiz_list %}
    <!-- The hardcodded url-->
       <!-- <li><a href="/each_quiz/{{ question.id }}/">{{ question.question_txt }}</a></li>

       -->
       <!--A better and Dynamic URL with url name-->
       <li><a href="{% url 'pollsite:detail' question.id %}">{{ question.question_txt }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </body>
</html>

qasite/pollsite/templates/pollsite/result.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>results</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        {% comment %} Results implementation {% endcomment %}

        <h1>{{ question.question_txt }}</h1>

        <ul>
        {% for ans in question.answer_set.all %}
            <li>{{ ans.answer_txt }} 	&#10132; {{ ans.votes }} votes</li>
        {% endfor %}
        </ul>

        
        <!--Redirect to the exact question page to revote-->
        <a href="{% url 'pollsite:detail' question.id %}">Vote again?</a>
        
        <script src="" async defer></script>
    </body>
</html>